version: "3.8"

services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4173:4173"
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src
    depends_on:
      - node_backend

  node_backend:
    build: ./backend
    container_name: node_backend
    ports: 
      - "9996:9996"
    volumes:
      - ./backend:/app/node_backend
