version: "3.8"

services:
  frontend:
    build: ./frontend
    networks: 
      sina:
        ipv4_address: 172.11.1.9
    container_name: frontend
    ports:
      - "4173:4173"
    depends_on:
      - node_backend

  node_backend:
    build: ./backend
    container_name: node_backend
    networks: 
      sina:
        ipv4_address: 172.11.1.10
    ports: 
      - "9996:9996"

networks:
  sina:
    ipam:
      driver: default
      config: 
        - subnet: 172.11.0.0/16